/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:51284732-74fc-459b-bde7-9b3c2bc622fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aY9AJmcBC",
    "aws_user_pools_web_client_id": "33b4unl8bvtnam63sjg9cs6mgh",
    "oauth": {}
};


export default awsmobile;
